# PR Check
#
# This Action setup Go, build and test the code and perform a dependency review
#
name: 'PR check'
on: [pull_request]

permissions:
  contents: read

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      # Setup Go
      - name: 'Setup Go'
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: ./go.sum

      # Build
      - name: 'Build code'
        run: make build

      # Test
      - name: 'Test code'
        run: make test

      # Review dependencies
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          fail-on-severity: high
